"""
CL10: Sorting in Python
Companion to CL10_SortingAcrossLanguages.java

Python has the cleanest sorting API of any language:
- sorted() returns a new list; list.sort() is in-place
- key= parameter replaces Comparator
- No gotcha: numeric sort is always numeric

Run: python3 CL10_Sorting.py
"""

from dataclasses import dataclass
import operator
import bisect

print("=== 1. BASIC SORT ===\n")

nums = [5, 2, 8, 1, 9, 3]
words = ["banana", "apple", "cherry", "date"]

nums_sorted = sorted(nums)         # new list — original unchanged
words_sorted = sorted(words)       # alphabetical by default

nums.sort()                        # in-place — modifies original

print(f"sorted (new):     {nums_sorted}")
print(f"words sorted:     {words_sorted}")
print(f"nums after sort:  {nums}")

# Descending
print(f"descending:       {sorted(nums, reverse=True)}")

print("\n=== 2. SORT WITH KEY ===\n")

print(f"by length:        {sorted(words, key=len)}")
print(f"by length desc:   {sorted(words, key=len, reverse=True)}")
print(f"case-insensitive: {sorted(['Banana','apple','Cherry'], key=str.lower)}")

# Lambda key
print(f"by last char:     {sorted(words, key=lambda w: w[-1])}")

print("\n=== 3. SORT OBJECTS ===\n")

@dataclass
class Person:
    name: str
    age: int
    def __repr__(self):
        return f"{self.name}({self.age})"

people = [
    Person("Charlie", 30),
    Person("Alice", 25),
    Person("Dave", 25),
    Person("Bob", 35)
]

by_age  = sorted(people, key=lambda p: p.age)
by_name = sorted(people, key=lambda p: p.name)
by_age_name = sorted(people, key=lambda p: (p.age, p.name))  # tuple key!

print(f"by age:           {by_age}")
print(f"by name:          {by_name}")
print(f"by age then name: {by_age_name}")

# operator.attrgetter — more efficient for simple attribute access
by_age2 = sorted(people, key=operator.attrgetter('age'))
print(f"attrgetter:       {by_age2}")

print("\n=== 4. COMPARABLE — __lt__ METHOD ===\n")

@dataclass(order=True)  # auto-generates comparison methods
class Score:
    value: int
    label: str

scores = [Score(85, "B"), Score(95, "A"), Score(70, "C")]
print(f"sorted scores: {sorted(scores)}")   # uses __lt__ generated by @dataclass

print("\n=== 5. SORT IS STABLE ===\n")

# Python's sort is stable — equal elements preserve original order
data = [("Alice", 25), ("Bob", 25), ("Charlie", 30)]
# Sort by age — Alice and Bob keep their relative order (stable)
by_age_stable = sorted(data, key=lambda x: x[1])
print(f"stable sort: {by_age_stable}")

print("\n=== 6. BINARY SEARCH (bisect module) ===\n")

lst = [1, 3, 5, 7, 9, 11]

idx = bisect.bisect_left(lst, 7)     # index of 7
print(f"bisect_left(7):  {idx}")     # 3

idx_missing = bisect.bisect_left(lst, 6)
print(f"bisect_left(6):  {idx_missing} (insertion point)")  # 3

# bisect_right: insertion point AFTER existing matches
print(f"bisect_right(7): {bisect.bisect_right(lst, 7)}")   # 4

# Insert in sorted order
bisect.insort(lst, 6)
print(f"after insort(6): {lst}")

print("\n=== KEY DIFFERENCES FROM JAVA ===\n")
print("Python sorted() returns NEW list; Java Collections.sort() is in-place")
print("Python key= replaces Java Comparator (much simpler!)")
print("Python tuple key handles multi-key: key=lambda p: (p.age, p.name)")
print("Python bisect replaces Java Arrays.binarySearch")
print("No gotcha: Python numeric sort is always numeric (no JS-style string bug)")
